name: Publish to npm

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm ci

      - name: Sync package.json version from Git tag
        run: |
          # GITHUB_REF is like "refs/tags/v1.2.3"
          TAG=${GITHUB_REF#refs/tags/}
          # if your tags include a "v" prefix, strip it:
          VER=${TAG#v}
          echo "🔖 Git tag is $TAG → setting version to $VER"
          npm version $VER --no-git-tag-version

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
